import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import '@/styles/globals.scss';

import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: '모시',
  description: 'Generated by create next app',
};

declare global {
  // eslint-disable-next-line no-unused-vars
  interface Window {
    Kakao: any;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <script src="https://t1.kakaocdn.net/kakao_js_sdk/2.7.2/kakao.min.js" crossOrigin="anonymous"></script>
        <script>dayjs.extend(window.dayjs_plugin_isBetween)</script>
        <link rel="shortcut icon" href="#" />
        <link
          rel="preload"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css"
        />
      </head>
      <body className="root_container">
        <div className="root_inner_container">{children}</div>
      </body>
    </html>
  );
}
