import '@/styles/index.scss';

import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: '모시',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="preload"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css"
        />
      </head>
      <body className="root_container">
        <div className="root_inner_container">{children}</div>
      </body>
    </html>
  );
}
